logging:
  level:
    org:
      springframework:
        nodeValue: INFO
        web: DEBUG
      springdoc: DEBUG
spring:
  appliation:
    name: FILE-SERVICE
server:
  port: '8091'
springdoc:
  swagger-ui:
    enabled: 'true'
